modLoader = "javafml"
loaderVersion = "[38,)"
license = "LGPL"

[[mods]]
modId = "bobby"
version = "5.0.0"
displayName = "Bobby Reforged"
description = "Allows for render distances greater than the server's view-distance setting."

[[dependencies.bobby]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.bobby]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "CLIENT"
